-- ============================================================
-- gakudo baseline schema (consolidated)
--
-- Pre-launch (production users = 0) baseline, generated by
-- concatenating the previous 13 migrations in apply order:
--
--   00001_initial_schema           — core tables (profiles, children, attendances, etc.)
--   00002_rls_policies             — RLS for all application tables
--   00003_storage_policies         — RLS for storage.objects (photos, documents)
--   00004_site_pages_metadata      — site_pages.metadata column + seed
--   00005_attachments              — attachments table for announcements/news
--   00006_entrance_role            — extend role CHECK to allow 'entrance'
--   00007_inquiries                — public inquiry form table
--   00008_instagram_posts          — admin-curated Instagram URL list
--   00009_attendance_summary_rpc   — get_attendance_summary RPC
--   00010_announcement_recipients  — targeted announcement model + can_view_announcement()
--   00011_perf_indexes             — performance indexes
--   00012_rate_limit_log           — IP/email rate limiting table
--   00013_site_news_revisions      — site_news edit history (audit trail)
--
-- The original 13 migration files were removed in this commit. Per-
-- file history is preserved in git log (`git log --diff-filter=D` for
-- the deletion commit). New schema changes go in fresh
-- 00002_*.sql, 00003_*.sql, ... files appended on top of this baseline.
-- ============================================================


-- ============================================================
-- Section from: 00001_initial_schema.sql
-- ============================================================

-- ============================================================
-- 学童保育管理システム 初期スキーマ
-- ============================================================

-- updated_at 自動更新トリガー関数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- プロフィール（Supabase Auth と連携）
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('parent', 'teacher', 'admin')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TRIGGER trg_profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- 児童
-- ============================================================
CREATE TABLE IF NOT EXISTS children (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 6),
  qr_code TEXT UNIQUE NOT NULL,
  qr_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TRIGGER trg_children_updated_at
  BEFORE UPDATE ON children
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- 児童と保護者の多対多リレーション
-- ============================================================
CREATE TABLE IF NOT EXISTS child_parents (
  child_id UUID REFERENCES children(id) ON DELETE CASCADE,
  parent_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  PRIMARY KEY (child_id, parent_id)
);

-- ============================================================
-- 入退室記録
-- ============================================================
CREATE TABLE IF NOT EXISTS attendances (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id UUID NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('enter', 'exit')),
  method TEXT NOT NULL CHECK (method IN ('qr', 'manual')),
  recorded_at TIMESTAMPTZ DEFAULT now(),
  recorded_by UUID REFERENCES profiles(id)
);

CREATE INDEX IF NOT EXISTS idx_attendances_child_date
  ON attendances (child_id, recorded_at);

-- ============================================================
-- お知らせ
-- ============================================================
CREATE TABLE IF NOT EXISTS announcements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  posted_by UUID NOT NULL REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- お知らせ既読管理
-- ============================================================
CREATE TABLE IF NOT EXISTS announcement_reads (
  announcement_id UUID REFERENCES announcements(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  read_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (announcement_id, user_id)
);

-- ============================================================
-- 写真
-- ============================================================
CREATE TABLE IF NOT EXISTS photos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  storage_path TEXT NOT NULL,
  thumbnail_path TEXT,
  caption TEXT,
  event_name TEXT,
  visibility TEXT NOT NULL DEFAULT 'private' CHECK (visibility IN ('private', 'public')),
  uploaded_by UUID NOT NULL REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 書類・ドキュメント
-- ============================================================
CREATE TABLE IF NOT EXISTS documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  file_path TEXT NOT NULL,
  category TEXT NOT NULL,
  uploaded_by UUID NOT NULL REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 延長保育料金ルール
-- ============================================================
CREATE TABLE IF NOT EXISTS billing_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  regular_end_time TIME NOT NULL,
  rate_per_unit INTEGER NOT NULL,
  unit_minutes INTEGER NOT NULL DEFAULT 30,
  effective_from DATE NOT NULL,
  created_by UUID NOT NULL REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 月次請求
-- ============================================================
CREATE TABLE IF NOT EXISTS monthly_bills (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  child_id UUID NOT NULL REFERENCES children(id),
  year_month TEXT NOT NULL,
  total_extended_minutes INTEGER NOT NULL DEFAULT 0,
  total_amount INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'confirmed')),
  confirmed_at TIMESTAMPTZ,
  confirmed_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (child_id, year_month)
);

-- ============================================================
-- 公開サイト 固定ページ
-- ============================================================
CREATE TABLE IF NOT EXISTS site_pages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now(),
  updated_by UUID REFERENCES profiles(id)
);

CREATE TRIGGER trg_site_pages_updated_at
  BEFORE UPDATE ON site_pages
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- 公開サイト ニュース
-- ============================================================
CREATE TABLE IF NOT EXISTS site_news (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  published_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID REFERENCES profiles(id)
);

-- ============================================================
-- 通知設定
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  method TEXT NOT NULL DEFAULT 'email' CHECK (method IN ('push', 'email', 'both', 'off'))
);

-- ============================================================
-- プッシュ通知サブスクリプション
-- ============================================================
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  subscription JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- Section from: 00002_rls_policies.sql
-- ============================================================

-- ============================================================
-- Row Level Security ポリシー
-- ============================================================

-- ============================================================
-- ヘルパー関数
-- ============================================================

-- ユーザーロール取得
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid()
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- 管理者判定
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- スタッフ判定（教員または管理者）
CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('teacher', 'admin'))
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- ============================================================
-- 全テーブル RLS 有効化
-- ============================================================
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE children ENABLE ROW LEVEL SECURITY;
ALTER TABLE child_parents ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcement_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE monthly_bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_news ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- profiles（プロフィール）
-- ============================================================

-- 認証済みユーザーは全プロフィールを閲覧可能（名前表示等に必要）
CREATE POLICY "profiles_select_authenticated"
  ON profiles FOR SELECT
  TO authenticated
  USING (true);

-- 挿入はトリガーまたは管理者（service role）のみ
-- RLS ポリシーなし = デフォルト拒否

-- 自分のプロフィールを更新可能、管理者は全員分を更新可能
CREATE POLICY "profiles_update_own_or_admin"
  ON profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid() OR is_admin())
  WITH CHECK (id = auth.uid() OR is_admin());

-- ============================================================
-- children（児童）
-- ============================================================

-- スタッフは全児童を閲覧可能、保護者は自分の子どものみ
CREATE POLICY "children_select"
  ON children FOR SELECT
  TO authenticated
  USING (
    is_staff()
    OR id IN (SELECT child_id FROM child_parents WHERE parent_id = auth.uid())
  );

-- 登録・更新・削除はスタッフのみ
CREATE POLICY "children_insert_staff"
  ON children FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

CREATE POLICY "children_update_staff"
  ON children FOR UPDATE
  TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

CREATE POLICY "children_delete_staff"
  ON children FOR DELETE
  TO authenticated
  USING (is_staff());

-- ============================================================
-- child_parents（児童と保護者のリレーション）
-- ============================================================

-- スタッフは全件閲覧可能、保護者は自分の行のみ
CREATE POLICY "child_parents_select"
  ON child_parents FOR SELECT
  TO authenticated
  USING (
    is_staff()
    OR parent_id = auth.uid()
  );

-- 登録・削除はスタッフのみ
CREATE POLICY "child_parents_insert_staff"
  ON child_parents FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

CREATE POLICY "child_parents_delete_staff"
  ON child_parents FOR DELETE
  TO authenticated
  USING (is_staff());

-- ============================================================
-- attendances（入退室記録）
-- ============================================================

-- スタッフは全件閲覧可能、保護者は自分の子どもの記録のみ
CREATE POLICY "attendances_select"
  ON attendances FOR SELECT
  TO authenticated
  USING (
    is_staff()
    OR child_id IN (SELECT child_id FROM child_parents WHERE parent_id = auth.uid())
  );

-- 登録はスタッフのみ（教員・管理者が記録）
CREATE POLICY "attendances_insert_staff"
  ON attendances FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

-- 更新・削除は管理者のみ
CREATE POLICY "attendances_update_admin"
  ON attendances FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "attendances_delete_admin"
  ON attendances FOR DELETE
  TO authenticated
  USING (is_admin());

-- ============================================================
-- announcements（お知らせ）
-- ============================================================

-- 認証済みユーザーは全件閲覧可能
CREATE POLICY "announcements_select_authenticated"
  ON announcements FOR SELECT
  TO authenticated
  USING (true);

-- 投稿はスタッフのみ
CREATE POLICY "announcements_insert_staff"
  ON announcements FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

-- 更新は管理者または投稿者本人（スタッフに限る）
CREATE POLICY "announcements_update"
  ON announcements FOR UPDATE
  TO authenticated
  USING (is_admin() OR (posted_by = auth.uid() AND is_staff()))
  WITH CHECK (is_admin() OR (posted_by = auth.uid() AND is_staff()));

-- 削除は管理者または投稿者本人（スタッフに限る）
CREATE POLICY "announcements_delete"
  ON announcements FOR DELETE
  TO authenticated
  USING (is_admin() OR (posted_by = auth.uid() AND is_staff()));

-- ============================================================
-- announcement_reads（お知らせ既読管理）
-- ============================================================

-- 自分の既読またはスタッフは全件閲覧可能
CREATE POLICY "announcement_reads_select"
  ON announcement_reads FOR SELECT
  TO authenticated
  USING (
    user_id = auth.uid()
    OR is_staff()
  );

-- 自分の既読のみ登録可能
CREATE POLICY "announcement_reads_insert_own"
  ON announcement_reads FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- 削除は管理者のみ
CREATE POLICY "announcement_reads_delete_admin"
  ON announcement_reads FOR DELETE
  TO authenticated
  USING (is_admin());

-- ============================================================
-- photos（写真）
-- ============================================================

-- スタッフは全件閲覧可能、認証済みユーザーはプライベート写真を閲覧可能、公開写真は全員閲覧可能
CREATE POLICY "photos_select_authenticated"
  ON photos FOR SELECT
  TO authenticated
  USING (
    is_staff()
    OR visibility = 'public'
    OR visibility = 'private'
  );

-- 公開写真は匿名ユーザーも閲覧可能
CREATE POLICY "photos_select_anon"
  ON photos FOR SELECT
  TO anon
  USING (visibility = 'public');

-- アップロードはスタッフのみ
CREATE POLICY "photos_insert_staff"
  ON photos FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

-- 更新は管理者またはアップロード者
CREATE POLICY "photos_update"
  ON photos FOR UPDATE
  TO authenticated
  USING (is_admin() OR uploaded_by = auth.uid())
  WITH CHECK (is_admin() OR uploaded_by = auth.uid());

-- 削除は管理者またはアップロード者
CREATE POLICY "photos_delete"
  ON photos FOR DELETE
  TO authenticated
  USING (is_admin() OR uploaded_by = auth.uid());

-- ============================================================
-- documents（書類・ドキュメント）
-- ============================================================

-- 認証済みユーザーは全件閲覧可能
CREATE POLICY "documents_select_authenticated"
  ON documents FOR SELECT
  TO authenticated
  USING (true);

-- アップロードはスタッフのみ
CREATE POLICY "documents_insert_staff"
  ON documents FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

-- 更新は管理者またはアップロード者
CREATE POLICY "documents_update"
  ON documents FOR UPDATE
  TO authenticated
  USING (is_admin() OR uploaded_by = auth.uid())
  WITH CHECK (is_admin() OR uploaded_by = auth.uid());

-- 削除は管理者またはアップロード者
CREATE POLICY "documents_delete"
  ON documents FOR DELETE
  TO authenticated
  USING (is_admin() OR uploaded_by = auth.uid());

-- ============================================================
-- billing_rules（延長保育料金ルール）
-- ============================================================

-- 認証済みユーザーは閲覧可能（料金表示に必要）
CREATE POLICY "billing_rules_select_authenticated"
  ON billing_rules FOR SELECT
  TO authenticated
  USING (true);

-- 登録・更新は管理者のみ
CREATE POLICY "billing_rules_insert_admin"
  ON billing_rules FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "billing_rules_update_admin"
  ON billing_rules FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- ============================================================
-- monthly_bills（月次請求）
-- ============================================================

-- スタッフは全件閲覧可能、保護者は自分の子どもの請求のみ
CREATE POLICY "monthly_bills_select"
  ON monthly_bills FOR SELECT
  TO authenticated
  USING (
    is_staff()
    OR child_id IN (SELECT child_id FROM child_parents WHERE parent_id = auth.uid())
  );

-- 登録・更新はスタッフのみ（システム計算）
CREATE POLICY "monthly_bills_insert_staff"
  ON monthly_bills FOR INSERT
  TO authenticated
  WITH CHECK (is_staff());

CREATE POLICY "monthly_bills_update_staff"
  ON monthly_bills FOR UPDATE
  TO authenticated
  USING (is_staff())
  WITH CHECK (is_staff());

-- ============================================================
-- site_pages（公開サイト固定ページ）
-- ============================================================

-- 匿名・認証済みユーザーともに閲覧可能（公開ホームページ用）
CREATE POLICY "site_pages_select_public"
  ON site_pages FOR SELECT
  TO anon, authenticated
  USING (true);

-- 登録・更新は管理者のみ
CREATE POLICY "site_pages_insert_admin"
  ON site_pages FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "site_pages_update_admin"
  ON site_pages FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

-- ============================================================
-- site_news（公開サイトニュース）
-- ============================================================

-- 匿名・認証済みユーザーともに閲覧可能（公開ホームページ用）
CREATE POLICY "site_news_select_public"
  ON site_news FOR SELECT
  TO anon, authenticated
  USING (true);

-- 登録・更新・削除は管理者のみ
CREATE POLICY "site_news_insert_admin"
  ON site_news FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());

CREATE POLICY "site_news_update_admin"
  ON site_news FOR UPDATE
  TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());

CREATE POLICY "site_news_delete_admin"
  ON site_news FOR DELETE
  TO authenticated
  USING (is_admin());

-- ============================================================
-- notification_preferences（通知設定）
-- ============================================================

-- 自分の設定のみ閲覧可能
CREATE POLICY "notification_preferences_select_own"
  ON notification_preferences FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- 自分の設定のみ登録可能
CREATE POLICY "notification_preferences_insert_own"
  ON notification_preferences FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- 自分の設定のみ更新可能
CREATE POLICY "notification_preferences_update_own"
  ON notification_preferences FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- ============================================================
-- push_subscriptions（プッシュ通知サブスクリプション）
-- ============================================================

-- 自分のサブスクリプションのみ閲覧可能
CREATE POLICY "push_subscriptions_select_own"
  ON push_subscriptions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

-- 自分のサブスクリプションのみ登録可能
CREATE POLICY "push_subscriptions_insert_own"
  ON push_subscriptions FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- 自分のサブスクリプションまたは管理者が削除可能
CREATE POLICY "push_subscriptions_delete"
  ON push_subscriptions FOR DELETE
  TO authenticated
  USING (user_id = auth.uid() OR is_admin());

-- ============================================================
-- Section from: 00003_storage_policies.sql
-- ============================================================

-- ============================================================
-- Storage バケット RLS ポリシー
-- ============================================================

-- photos バケット: 認証済みユーザーが読み取り、admin/teacher がアップロード・削除
CREATE POLICY "photos_select" ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'photos');

CREATE POLICY "photos_insert" ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'photos'
    AND EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role IN ('admin', 'teacher')
    )
  );

CREATE POLICY "photos_delete" ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'photos'
    AND EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role IN ('admin', 'teacher')
    )
  );

-- documents バケット: 認証済みユーザーが読み取り、admin がアップロード・削除
CREATE POLICY "documents_select" ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'documents');

CREATE POLICY "documents_insert" ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'documents'
    AND EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE POLICY "documents_delete" ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'documents'
    AND EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- ============================================================
-- Section from: 00004_site_pages_metadata.sql
-- ============================================================

-- site_pages に metadata JSONB カラムを追加
-- ページ種別ごとの構造化データ（サブタイトル、スケジュール、施設概要など）を格納
ALTER TABLE site_pages
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

-- 既存の about ページにデフォルトメタデータを設定
UPDATE site_pages SET metadata = '{
  "subtitle": "子どもたちが「ただいま！」と駆け込んでくる、あたたかい居場所です。",
  "vision_heading": "私たちの想い",
  "vision_emoji": "🏠",
  "vision_tagline": "家庭のようなあたたかさ",
  "schedule": [
    { "time": "14:00", "label": "入室・宿題タイム", "emoji": "📝" },
    { "time": "15:30", "label": "おやつ", "emoji": "🍪" },
    { "time": "16:00", "label": "自由遊び・活動", "emoji": "⚽" },
    { "time": "18:00", "label": "お迎え・退室", "emoji": "👋" }
  ],
  "facility_info": [
    { "label": "施設名", "value": "星ヶ丘こどもクラブ" },
    { "label": "運営形態", "value": "父母運営型 学童保育" },
    { "label": "対象", "value": "小学1〜6年生" },
    { "label": "定員", "value": "約30名" },
    { "label": "開所時間", "value": "平日 放課後〜19:00 / 土曜・長期休暇 8:00〜19:00" },
    { "label": "休所日", "value": "日曜・祝日・年末年始" }
  ]
}'::jsonb WHERE slug = 'about';

-- 既存の access ページにデフォルトメタデータを設定
UPDATE site_pages SET metadata = '{
  "subtitle": "お気軽にお越しください。見学も随時受け付けております。",
  "phone": "03-1234-5678",
  "phone_hours": "受付: 平日 9:00〜18:00",
  "opening_hours": "平日: 放課後〜19:00\n土曜・長期休暇: 8:00〜19:00",
  "visit_heading": "見学のお申し込み",
  "visit_text": "入所をご検討中の方は、お気軽にお電話ください。\n施設の見学は随時受け付けております。"
}'::jsonb WHERE slug = 'access';

-- 既存の home ページにデフォルトメタデータを設定
UPDATE site_pages SET metadata = '{
  "subtitle": "星ヶ丘こどもクラブは、保護者の手で運営する学童保育施設です。"
}'::jsonb WHERE slug = 'home';

-- ============================================================
-- Section from: 00005_attachments.sql
-- ============================================================

-- ============================================================
-- 添付ファイル管理テーブル + ストレージバケット
-- ============================================================

-- attachments ストレージバケット作成
INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', false)
ON CONFLICT (id) DO NOTHING;

-- attachments バケットのRLSポリシー
-- 読み取り: 認証済みユーザー
CREATE POLICY "attachments_select" ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'attachments');

-- 公開ページ向け（お知らせの添付ファイル）: anonでも読み取り可能
CREATE POLICY "attachments_select_anon" ON storage.objects FOR SELECT
  TO anon
  USING (bucket_id = 'attachments' AND (storage.foldername(name))[1] = 'news');

-- アップロード: staff (admin/teacher)
CREATE POLICY "attachments_insert" ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'attachments'
    AND EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role IN ('admin', 'teacher')
    )
  );

-- 削除: staff (admin/teacher)
CREATE POLICY "attachments_delete" ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'attachments'
    AND EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role IN ('admin', 'teacher')
    )
  );

-- 添付ファイル管理テーブル
CREATE TABLE IF NOT EXISTS attachments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity_type TEXT NOT NULL CHECK (entity_type IN ('announcement', 'news')),
  entity_id UUID NOT NULL,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  mime_type TEXT NOT NULL,
  uploaded_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_attachments_entity ON attachments(entity_type, entity_id);

-- RLS
ALTER TABLE attachments ENABLE ROW LEVEL SECURITY;

-- 読み取り: 認証済みユーザー全員
CREATE POLICY "attachments_row_select" ON attachments FOR SELECT
  TO authenticated
  USING (true);

-- 公開お知らせの添付は匿名でも閲覧可能
CREATE POLICY "attachments_row_select_anon" ON attachments FOR SELECT
  TO anon
  USING (entity_type = 'news');

-- 挿入: staff
CREATE POLICY "attachments_row_insert" ON attachments FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role IN ('admin', 'teacher')
    )
  );

-- 削除: staff
CREATE POLICY "attachments_row_delete" ON attachments FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE id = auth.uid() AND role IN ('admin', 'teacher')
    )
  );

-- ============================================================
-- Section from: 00006_entrance_role.sql
-- ============================================================

-- entranceロール追加（入口端末用）
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE profiles ADD CONSTRAINT profiles_role_check
  CHECK (role IN ('parent', 'teacher', 'admin', 'entrance'));

-- ============================================================
-- Section from: 00007_inquiries.sql
-- ============================================================

-- 見学予約・お問い合わせテーブル
CREATE TABLE inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL CHECK (type IN ('visit', 'general')),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  preferred_date TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'declined', 'replied')),
  admin_reply TEXT,
  replied_at TIMESTAMPTZ,
  replied_by UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- インデックス
CREATE INDEX idx_inquiries_status ON inquiries(status);
CREATE INDEX idx_inquiries_created_at ON inquiries(created_at DESC);

-- RLS有効化
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- 匿名ユーザー（未認証含む）はINSERTのみ
CREATE POLICY "Anyone can submit inquiry"
  ON inquiries FOR INSERT
  WITH CHECK (true);

-- admin/teacherは全件閲覧可能
CREATE POLICY "Staff can view inquiries"
  ON inquiries FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'teacher')
    )
  );

-- admin/teacherは更新可能（返信時のステータス更新用）
CREATE POLICY "Staff can update inquiries"
  ON inquiries FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'teacher')
    )
  );

-- ============================================================
-- Section from: 00008_instagram_posts.sql
-- ============================================================

-- Instagram投稿の埋め込み管理テーブル
CREATE TABLE instagram_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_url TEXT NOT NULL,
  caption TEXT,
  display_order INT NOT NULL DEFAULT 0,
  is_visible BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID REFERENCES profiles(id)
);

-- RLS
ALTER TABLE instagram_posts ENABLE ROW LEVEL SECURITY;

-- 誰でも閲覧可（公開ギャラリー用）
CREATE POLICY "instagram_posts_select" ON instagram_posts
  FOR SELECT USING (true);

-- admin/teacher のみ INSERT/UPDATE/DELETE
CREATE POLICY "instagram_posts_insert" ON instagram_posts
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
  );

CREATE POLICY "instagram_posts_update" ON instagram_posts
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
  );

CREATE POLICY "instagram_posts_delete" ON instagram_posts
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
  );

-- ============================================================
-- Section from: 00009_attendance_summary_rpc.sql
-- ============================================================

-- RPC function: returns anonymous attendance summary counts for today
-- Accessible by any authenticated user (parents can see how many children are present)
CREATE OR REPLACE FUNCTION get_attendance_summary()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  total_children INT;
  entered_count INT;
  exited_count INT;
  jst_start TIMESTAMPTZ;
  jst_end TIMESTAMPTZ;
BEGIN
  -- Calculate today's range in JST (UTC+9)
  jst_start := date_trunc('day', now() AT TIME ZONE 'Asia/Tokyo') AT TIME ZONE 'Asia/Tokyo';
  jst_end := jst_start + interval '1 day';

  SELECT COUNT(*) INTO total_children FROM children;

  -- Get latest attendance type per child today
  WITH latest AS (
    SELECT DISTINCT ON (child_id) child_id, type
    FROM attendances
    WHERE recorded_at >= jst_start AND recorded_at < jst_end
    ORDER BY child_id, recorded_at DESC
  )
  SELECT
    COUNT(*) FILTER (WHERE type = 'enter'),
    COUNT(*) FILTER (WHERE type = 'exit')
  INTO entered_count, exited_count
  FROM latest;

  RETURN json_build_object(
    'total', total_children,
    'entered', COALESCE(entered_count, 0),
    'exited', COALESCE(exited_count, 0),
    'none', total_children - COALESCE(entered_count, 0) - COALESCE(exited_count, 0)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION get_attendance_summary() TO authenticated;

-- ============================================================
-- Section from: 00010_announcement_recipients.sql
-- ============================================================

-- ============================================================
-- お知らせの送信対象（全員／個別ユーザー）
-- ============================================================
--
-- これまで announcements は全認証ユーザーへ一斉公開されていた。
-- 先生・管理者が「全員」または「個別ユーザー」を選んで送れるよう、
-- 対象テーブルを追加する。
--
-- recipient_type:
--   'all'  : 全保護者向け（recipient_user_id は NULL）
--   'user' : 個別ユーザー（recipient_user_id に profiles.id を格納）
--
-- 1つの announcement に対して 'user' 行を複数挿入することで
-- 「保護者A・Bだけ」のような個別宛先を表現できる。
-- 'all' と 'user' の併用は不要なため 'all' は1行に限定する。

CREATE TABLE IF NOT EXISTS announcement_recipients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  announcement_id UUID NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  recipient_type TEXT NOT NULL CHECK (recipient_type IN ('all', 'user')),
  recipient_user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT now(),
  CONSTRAINT announcement_recipients_value_check CHECK (
    (recipient_type = 'all'  AND recipient_user_id IS NULL)
    OR (recipient_type = 'user' AND recipient_user_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_announcement_recipients_announcement
  ON announcement_recipients (announcement_id);

CREATE INDEX IF NOT EXISTS idx_announcement_recipients_user
  ON announcement_recipients (recipient_user_id)
  WHERE recipient_user_id IS NOT NULL;

-- 同一お知らせ内での重複行を防止
CREATE UNIQUE INDEX IF NOT EXISTS uniq_announcement_recipients_all
  ON announcement_recipients (announcement_id)
  WHERE recipient_type = 'all';

CREATE UNIQUE INDEX IF NOT EXISTS uniq_announcement_recipients_user
  ON announcement_recipients (announcement_id, recipient_user_id)
  WHERE recipient_type = 'user';

-- ============================================================
-- 既存お知らせのバックフィル（全件 'all' 扱い）
-- ============================================================
INSERT INTO announcement_recipients (announcement_id, recipient_type)
  SELECT a.id, 'all'
  FROM announcements a
  WHERE NOT EXISTS (
    SELECT 1 FROM announcement_recipients ar WHERE ar.announcement_id = a.id
  );

-- ============================================================
-- 閲覧権限ヘルパー
-- ============================================================
-- announcement_recipients の RLS が announcements の SELECT 内で再帰的に
-- 効くと厄介なので、SECURITY DEFINER の関数で対象判定を一括化する。
CREATE OR REPLACE FUNCTION public.can_view_announcement(p_announcement_id UUID)
RETURNS BOOLEAN AS $$
  SELECT public.is_staff()
    OR EXISTS (
      SELECT 1
      FROM public.announcement_recipients ar
      WHERE ar.announcement_id = p_announcement_id
        AND (
          ar.recipient_type = 'all'
          OR (ar.recipient_type = 'user' AND ar.recipient_user_id = auth.uid())
        )
    )
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- ============================================================
-- announcements の SELECT を「対象判定」ベースに差し替え
-- ============================================================
DROP POLICY IF EXISTS "announcements_select_authenticated" ON announcements;

CREATE POLICY "announcements_select_targeted"
  ON announcements FOR SELECT
  TO authenticated
  USING (public.can_view_announcement(id));

-- ============================================================
-- announcement_recipients の RLS
-- ============================================================
ALTER TABLE announcement_recipients ENABLE ROW LEVEL SECURITY;

-- スタッフは全件、保護者は自分が閲覧可能なお知らせの行だけ閲覧可
CREATE POLICY "announcement_recipients_select"
  ON announcement_recipients FOR SELECT
  TO authenticated
  USING (
    public.is_staff()
    OR public.can_view_announcement(announcement_id)
  );

-- 登録・更新・削除はスタッフのみ
CREATE POLICY "announcement_recipients_insert_staff"
  ON announcement_recipients FOR INSERT
  TO authenticated
  WITH CHECK (public.is_staff());

CREATE POLICY "announcement_recipients_update_staff"
  ON announcement_recipients FOR UPDATE
  TO authenticated
  USING (public.is_staff())
  WITH CHECK (public.is_staff());

CREATE POLICY "announcement_recipients_delete_staff"
  ON announcement_recipients FOR DELETE
  TO authenticated
  USING (public.is_staff());

-- ============================================================
-- Section from: 00011_perf_indexes.sql
-- ============================================================

-- ============================================================
-- Phase 1-C: Performance indexes for hot lookup paths
-- ============================================================
--
-- Plain CREATE INDEX (not CONCURRENTLY) because Supabase migrations
-- run inside a transaction. For production rollout on a hot table,
-- run an ad-hoc CREATE INDEX CONCURRENTLY first, then this migration
-- becomes a no-op via IF NOT EXISTS.
--
-- Coverage rationale:
--
-- 1. child_parents(parent_id)
--    Backed query: src/lib/announcements/recipients-server.ts
--      .from("child_parents").select(...).in("parent_id", ids)
--    The PRIMARY KEY is (child_id, parent_id) so parent_id alone is
--    not indexable via the PK. Without this, IN-list lookups scan.
--
-- 2. push_subscriptions(user_id)
--    Backed query: src/lib/notifications/send.ts (sendPushNotifications)
--      .from("push_subscriptions").select(...).in("user_id", userIds)
--    Currently no user_id index — every fan-out scans the whole table.
--    With Phase 1-A's parallel push, this scan would be the new
--    bottleneck.
--
-- 3. monthly_bills(year_month, status)
--    Backed queries: src/app/(dashboard)/billing/actions.ts
--      .eq("year_month", ym).eq("status", "draft")
--    UNIQUE (child_id, year_month) covers (year_month) only as the
--    second column. Composite (year_month, status) speeds the
--    confirm/list flow.
--
-- 4. announcement_reads(user_id)
--    Backed query: src/components/nav/get-badge-counts.ts (unread)
--    Plus exists() lookups for unread badges.
--    PRIMARY KEY is (announcement_id, user_id) so user_id alone is
--    not indexable from the PK; this index covers per-user lookups.
--
-- Skipped (already covered):
--   - inquiries(status): created in 00007_inquiries.sql
--   - attendances(child_id, recorded_at): created in
--     00001_initial_schema.sql (the asc index also serves desc scans).
--   - announcement_recipients(*): created in
--     00010_announcement_recipients.sql.

CREATE INDEX IF NOT EXISTS idx_child_parents_parent
  ON child_parents (parent_id);

CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user
  ON push_subscriptions (user_id);

CREATE INDEX IF NOT EXISTS idx_monthly_bills_yearmonth_status
  ON monthly_bills (year_month, status);

CREATE INDEX IF NOT EXISTS idx_announcement_reads_user
  ON announcement_reads (user_id);

-- ============================================================
-- Section from: 00012_rate_limit_log.sql
-- ============================================================

-- ============================================================
-- Phase 2-A.4: Self-hosted rate limit ledger
-- ============================================================
--
-- Stores one row per "hit" for a given key (e.g. an IP address, an
-- email, or a composite of both). Callers count hits within a sliding
-- window via lib/ratelimit/check.ts to decide allow/deny.
--
-- Why a table instead of an external service:
--   - The plan explicitly favors self-hosted over @upstash/ratelimit.
--   - Supabase Postgres is the single source of truth we already trust
--     for everything else; we don't have to deploy or pay for another
--     piece of infra.
--   - Volume is low for the call sites we'll wire up (contact form,
--     password reset). A B-tree on (key, hit_at) handles them comfortably.
--
-- Hygiene:
--   - rate_limit_log_cleanup() drops rows older than 24 hours.
--   - Called best-effort from check.ts on a small percentage of
--     requests so we don't need pg_cron in the dev stack. Production
--     can also schedule it explicitly via Supabase scheduled jobs.

CREATE TABLE IF NOT EXISTS rate_limit_log (
  id BIGSERIAL PRIMARY KEY,
  key TEXT NOT NULL,
  hit_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rate_limit_log_key_hit_at
  ON rate_limit_log (key, hit_at DESC);

-- Service-role-only access; this table is internal plumbing and must
-- not be exposed to anon/authenticated traffic via PostgREST.
ALTER TABLE rate_limit_log ENABLE ROW LEVEL SECURITY;

-- No CREATE POLICY → with RLS enabled, only the service-role bypass
-- can read/write. This is intentional.

CREATE OR REPLACE FUNCTION public.rate_limit_log_cleanup()
RETURNS void AS $$
  DELETE FROM rate_limit_log
   WHERE hit_at < now() - INTERVAL '24 hours'
$$ LANGUAGE sql SECURITY DEFINER;

REVOKE ALL ON FUNCTION public.rate_limit_log_cleanup() FROM PUBLIC;

-- ============================================================
-- Section from: 00013_site_news_revisions.sql
-- ============================================================

-- Edit history for site_news.
--
-- The HP管理 > お知らせ管理 (admin/site/news) screen previously only let
-- admins create and delete entries; once posted there was no way to fix
-- a typo without losing audit trail. This migration adds:
--
--   1. site_news.updated_at / updated_by — tracks the latest edit on
--      the live row. Auto-maintained by a BEFORE UPDATE trigger so the
--      app code only has to set updated_by.
--   2. site_news_revisions — append-only snapshot table written
--      whenever the live row is updated. Captures the title, body, and
--      attachment metadata as it was BEFORE the change so admins can
--      see what each edit replaced.
--
-- The attachment list is denormalized into a JSONB column on the
-- revision so the snapshot keeps showing the file names + sizes that
-- existed at the time of the edit, even after the underlying
-- attachment rows have been deleted from the live table. The actual
-- file objects in storage are removed when an admin deletes the
-- attachment from the live row, so the JSONB metadata is the only
-- record kept (file_path is preserved but signed URLs to it stop
-- working once the storage object is gone — that's an accepted
-- trade-off since the user explicitly chose to remove the file).

ALTER TABLE site_news
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES profiles(id);

-- Auto-bump updated_at on every UPDATE. Existing rows get NOW() once
-- the trigger first fires; the DEFAULT above seeds them up front so
-- the column is sortable from day one.
CREATE OR REPLACE FUNCTION site_news_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS site_news_set_updated_at_trigger ON site_news;
CREATE TRIGGER site_news_set_updated_at_trigger
  BEFORE UPDATE ON site_news
  FOR EACH ROW
  EXECUTE FUNCTION site_news_set_updated_at();

-- Append-only revision history.
CREATE TABLE IF NOT EXISTS site_news_revisions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  news_id UUID NOT NULL REFERENCES site_news(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  -- Snapshot of attachments at the time of the edit. Shape:
  --   [{ id, file_name, file_path, file_size, mime_type }]
  attachments JSONB NOT NULL DEFAULT '[]'::jsonb,
  edited_by UUID REFERENCES profiles(id),
  edited_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS site_news_revisions_news_id_idx
  ON site_news_revisions (news_id, edited_at DESC);

-- RLS: revisions are an admin-only audit trail. Public users and
-- non-admin staff have no business reading prior versions of news copy.
ALTER TABLE site_news_revisions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "site_news_revisions_admin_select"
  ON site_news_revisions FOR SELECT
  TO authenticated
  USING (is_admin());

-- Inserts come exclusively from the updateNews server action which
-- runs with admin auth gated by withAuth + RLS; explicit policy keeps
-- the table append-only from the application side too.
CREATE POLICY "site_news_revisions_admin_insert"
  ON site_news_revisions FOR INSERT
  TO authenticated
  WITH CHECK (is_admin());
